"""Migration generated by Alembic."""

import sqlalchemy as sa
from alembic import op

revision = "9b01a03d5247"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "source_document",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("source_type", sa.String(length=80), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "target_record",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("entity_type", sa.String(length=80), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "external_identifier",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("target_record_id", sa.String(length=36), nullable=False),
        sa.Column("source_system", sa.String(length=100), nullable=False),
        sa.Column("source_identifier", sa.Text(), nullable=False),
        sa.Column("source_version", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["target_record_id"],
            ["target_record.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source_system",
            "source_identifier",
            "source_version",
            name="uq_external_identifier_reference",
        ),
    )
    op.create_table(
        "source_document_version",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("document_id", sa.String(length=36), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("source_version", sa.Text(), nullable=True),
        sa.Column("source_locator", sa.Text(), nullable=False),
        sa.Column("acquired_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["source_document.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "document_record_link",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("document_version_id", sa.String(length=36), nullable=False),
        sa.Column("target_record_id", sa.String(length=36), nullable=False),
        sa.Column("link_type", sa.String(length=80), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_version_id"],
            ["source_document_version.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_record_id"],
            ["target_record.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "source_fragment",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("document_version_id", sa.String(length=36), nullable=False),
        sa.Column("locator_type", sa.String(length=40), nullable=False),
        sa.Column("locator", sa.Text(), nullable=False),
        sa.Column("literal_text", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["document_version_id"],
            ["source_document_version.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "block_instance",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("target_record_id", sa.String(length=36), nullable=False),
        sa.Column("block_type", sa.String(length=120), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("source_fragment_id", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_fragment_id"],
            ["source_fragment.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_record_id"],
            ["target_record.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "target_record_link",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("source_record_id", sa.String(length=36), nullable=False),
        sa.Column("target_record_id", sa.String(length=36), nullable=False),
        sa.Column("link_type", sa.String(length=80), nullable=False),
        sa.Column("source_fragment_id", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_fragment_id"],
            ["source_fragment.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_record_id"],
            ["target_record.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_record_id"],
            ["target_record.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "field_value",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("block_instance_id", sa.String(length=36), nullable=False),
        sa.Column("field_name", sa.String(length=160), nullable=False),
        sa.Column("literal_value", sa.Text(), nullable=True),
        sa.Column("observed_type", sa.String(length=80), nullable=False),
        sa.Column("logical_state", sa.String(length=80), nullable=False),
        sa.ForeignKeyConstraint(
            ["block_instance_id"],
            ["block_instance.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "value_provenance",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("field_value_id", sa.String(length=36), nullable=False),
        sa.Column("source_fragment_id", sa.String(length=36), nullable=False),
        sa.Column("provenance_role", sa.String(length=80), nullable=False),
        sa.ForeignKeyConstraint(
            ["field_value_id"],
            ["field_value.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_fragment_id"],
            ["source_fragment.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("value_provenance")
    op.drop_table("field_value")
    op.drop_table("target_record_link")
    op.drop_table("block_instance")
    op.drop_table("source_fragment")
    op.drop_table("document_record_link")
    op.drop_table("source_document_version")
    op.drop_table("external_identifier")
    op.drop_table("target_record")
    op.drop_table("source_document")
    # ### end Alembic commands ###
